apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgAR/gc/yl783cIDSYoQQKBG0NdE1gPnQD1dLiJS3wfHjX2FpEwnG3AMgW8jMRS90+P5Z8JySsr9KS1N4abg6wCackVk7MHnQD1wetK8jiPUEQeVDke3/9cUb8Fpaoc1hRWsxQoXimZPCKtOZrgtLFvt2ns14il9CpWgBRGe/ZGJxgnhzSm2DSI3yxSmZwD13vRG/j6ktEGZgjl4baM3dr2Dqvswyu4KLDF09NrCVxoGFzKaipJyAsgfuDU9NCpcgRwG69D/97eYuWf/nYQSJPgTLvOgFvOEPxvhjVIOsECXIRfJwMMcBYwWwW8wmBjwpXKukSguwJm8xP6iqa8IpBjnbMD4Q+TbIQnfv2oonSPNI8/r41k+96i5rGzS/404MK6bTTdklb7DM2InBdQo60g3Kl2Y8HQnl6YTVeh+aaxN0ryOJ7Xxo/VbY2aWpV+QsPENeULu+3wAWRkkGatyxeQXXOAD1cbRIFDpKavZfGyk9eiVKJafl64GGNuzO8Tx/GE5Qs7h7wsAvb2VzsCasrR/JoLUGQsgcovdCoqZ4ia0RLlBr0/IPxryEy7kTTqBZzhsxjbcAcqC68wD8tYBR6BbCLYYUicw/YYiAZgrQ0FHsCiXJxh2urfktAvT8w8T2S59rLjWdZOT3bxqBBFTOKDRJ5uXTb2lHe2AL1htiX2Hyq+gI1RvQQyAIN7u6V4tWc4=
    user: AgCR+8qfioZhFRPlMNTaFjcdeHeJ6f51X3nyxTBSIxmCAJIlKX8x88xcZal8/r3iKerrswSAYuvPb3gtLVN0GCVqJF+UqM3+yRgj0s2VroR3K8T6KVXpinChVP0XZB6HgXpdZnNtRRR8Xd23ZcpPAzuo6QSQpL2kduhYlwQyigMqLtaCjLhruDRdIMFYZQzJ3EwtRKc8x8TEzo4g7IvzgQk/5+sUpt/7BAFGCKCDVAdLeS2cvUY9vExnaNLw1qUbOO3HELm4528O0nxcvaAeTghjkKizy6feiHUhtZsCU5Iu+2fwki2umFluRy+5hb3bxZ32lnxGxadX77d2FvsjhVWmdx0a/7zsuQe4mtOmpVCmSZlkafFMneEzW9acOmn87yo4p29KBRVkM4zBdi0uNKr74YDpk+IxjpPDBRTYUcU9QVzl8urbz4anrGkjP5UB07gzp2xFMpskung+ueyrcRQ8VKUPa0yTiiX/fZh9euD6SoOznwhSCcIRnFB7u/r3zf48RaYt4OuQh2tYNNrsWSSSDCHGBsKrGF55qCnnahWqXRbFMY5e1x3YRRJJVlrazkbIAu4jZqpeUVtu+yh+ZQ0EChSBDYup1Rdd3Z/pvVJefOkzkRKICXhv6VQqbcEIFoaqmRfABtReZty4QYZjYeBTjYyoFE3bZrVeGcJ8kKlqxGJGfiQ6bvf1Rii9y92ENThqKOSKN++8Ag==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default

